test steps.conclusion

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -48,7 +48,20 @@ jobs:
       matrix:
         version: [10, 12]
     steps:
-      - run: echo "running test ${{ matrix.version }}" && exit $((RANDOM % 2))
+      - name: run acceptance
+        id: run-acceptance
+        run: echo "running test ${{ matrix.version }}" && exit $((RANDOM % 2))
+      - name: re-run acceptance
+        if: steps.run-acceptance.conclusion == 'failure'
+        env:
+          steps_json: ${{ toJSON(steps) }}
+        run: echo "re-running test ${{ matrix.version }}"
+      - name: run if any steps fail
+        if: failure()
+        env:
+          steps_json: ${{ toJSON(steps) }}
+        run: echo "a step failed"
+        
   cache-runtime:
     runs-on: ubuntu-latest
     needs: ['rspec', 'acceptance']
