add merge-branches [skip ci]

diff --git a/.github/workflows/deploy-qa.yml b/.github/workflows/deploy-qa.yml
--- a/.github/workflows/deploy-qa.yml
+++ b/.github/workflows/deploy-qa.yml
@@ -10,52 +10,64 @@ on:
 jobs:
   merge-branches:
     runs-on: ubuntu-latest
-
+    env:
+      GH_TOKEN: ${{ github.token }}
+      BASE_BRANCH: main
+      REPO_NAME: ${{ github.repository }}
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
-
       - name: Create New Branch
         id: create-branch
-        env:
-          GH_TOKEN: ${{ github.token }}
+        continue-on-error: false
         run: |
-          INPUT_BRANCHES="${{ github.event.inputs.branches }}"
-          INPUT_BRANCHES="$(echo -e "${INPUT_BRANCHES}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
+          INPUT_BRANCHES="$(echo -e "${{ github.event.inputs.branches }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tr -s ' ' | tr ',' ' ')"
           TIMESTAMP=$(date +'%Y%m%d%H%M%S')
           NEW_BRANCH_NAME="merged-branches-${{ github.ref_name }}-$TIMESTAMP"
-          BASE_BRANCH=${{ github.ref_name }}
-          ACCESS_TOKEN="$GH_TOKEN"
-          REPO_NAME=${{ github.repository }}
-
-          # Create a new branch using the GitHub API
+          # Create a new branch from laster master
           curl -X POST \
-            -H "Authorization: token $ACCESS_TOKEN" \
+            -H "Authorization: token $GH_TOKEN" \
             -d '{
               "ref": "refs/heads/'$NEW_BRANCH_NAME'",
-              "sha": "'$(curl -s -H "Authorization: token $ACCESS_TOKEN" https://api.github.com/repos/$REPO_NAME/git/refs/heads/$BASE_BRANCH | jq -r '.object.sha')'"
+              "sha": "'$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO_NAME/git/refs/heads/$BASE_BRANCH | jq -r '.object.sha')'"
             }' \
             "https://api.github.com/repos/$REPO_NAME/git/refs"
 
           echo "New branch name: $NEW_BRANCH_NAME"
           echo "Input branches: $INPUT_BRANCHES"
+          echo "INPUT_BRANCHES=$INPUT_BRANCHES" >> $GITHUB_OUTPUT
+          echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_OUTPUT
+        
+      - name: Merge Branches
+        id: merge-branches
         continue-on-error: false
-
-      # - name: Merge Branches
-      #   run: |
-      #     INPUT_BRANCHES=${{ github.event.inputs.branches }}
-      #     for BRANCH in $INPUT_BRANCHES
-      #     do
-      #       # Merge branches using the GitHub API and `gh` CLI
-      #       gh api -X PUT "repos/$GITHUB_REPOSITORY/merges" -F base="$NEW_BRANCH_NAME" -F head="$BRANCH"
-      #       if [ $? -ne 0 ]
-      #       then
-      #         echo "Merge conflict or failure detected. Deleting the new branch."
-      #         git push origin --delete $NEW_BRANCH_NAME
-      #         exit 1
-      #       fi
-      #     done
-      #     echo "All branches merged successfully."
+        shell: bash -l {0}
+        run: |
+          BRANCHES_TO_MERGE="${{ github.ref_name }} ${{ steps.create-branch.outputs.INPUT_BRANCHES }}"
+          NEW_BRANCH_NAME=${{ steps.create-branch.outputs.NEW_BRANCH_NAME }}
+          echo "New branch name: $NEW_BRANCH_NAME"
+          echo "Branches to merge: $BRANCHES_TO_MERGE"
+          # Merge branches          
+          for BRANCH in $BRANCHES_TO_MERGE
+          do
+            echo "Merging $BRANCH"
+            gh api \
+              --method POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/$REPO_NAME/merges \
+              -f base="$NEW_BRANCH_NAME" \
+              -f head="$BRANCH" \
+              -f commit_message="Merge $BRANCH [skip ci]" \
+              --silent 
+            if [ $? -ne 0 ]
+            then
+              echo "Merge conflict or failure detected while merging $BRANCH. Deleting the new branch."
+              gh api -X DELETE "repos/$REPO_NAME/git/refs/heads/$NEW_BRANCH_NAME"
+              exit 1
+            fi
+          done
+          echo "All branches merged successfully."
 
       # - name: Push Merged Branch
       #   run: |
